-- Iniciar las transacciones
START TRANSACTION;

-- Insertar 10 filas en la tabla minutas
INSERT INTO minutas (orgName, meetingTitle, meetingDate, meetingTime, meetingPlace, facilitator, secretary, attendees, absentees, guests, agenda, discussion, newTopics, nextMeeting, closingTime, closingRemarks) VALUES
('Organización Alpha', 'Reunión Anual', '2023-01-15', '10:00:00', 'Sala A', 'Juan Pérez', 'María Gómez', 'Ana, Luis, Pedro', 'Marta, José', 'Carlos, Beatriz', '1. Introducción\n2. Reporte Anual\n3. Planificación', 'Se discutieron los logros del año pasado y las metas para el próximo año.', 'Implementación de nuevas tecnologías.', '2023-02-15', '12:00:00', 'Gracias a todos por su participación.'),
('Organización Beta', 'Reunión Mensual', '2023-02-10', '14:00:00', 'Sala B', 'Carlos Ruiz', 'Andrea Ramírez', 'Mónica, Javier, Laura', 'Eduardo, Silvia', 'Fernando, Patricia', '1. Informe Financiero\n2. Proyectos en curso\n3. Nuevas propuestas', 'Se revisaron los estados financieros y los avances de los proyectos en curso.', 'Propuesta de nuevos proyectos.', '2023-03-10', '16:00:00', 'Esperamos sus propuestas para la próxima reunión.'),
('Organización Gamma', 'Reunión de Progreso', '2023-03-05', '09:00:00', 'Sala C', 'Laura Sánchez', 'Fernando Torres', 'Alberto, Sonia, Miguel', 'Clara, Rafael', 'Lucía, Alejandro', '1. Revisión de Metas\n2. Evaluación de Progreso\n3. Ajustes Necesarios', 'Se evaluaron los progresos de los equipos y se ajustaron las metas.', 'Evaluación de nuevos métodos de trabajo.', '2023-04-05', '11:00:00', 'Agradecemos su compromiso y esfuerzo.'),
('Organización Delta', 'Reunión Estratégica', '2023-04-20', '13:00:00', 'Sala D', 'Miguel Ángel', 'Lucía Fernández', 'Isabel, Roberto, Teresa', 'Carmen, Francisco', 'David, Nuria', '1. Análisis de Mercado\n2. Estrategias de Crecimiento\n3. Plan de Acción', 'Se discutieron las estrategias de crecimiento basadas en el análisis de mercado.', 'Exploración de nuevos mercados.', '2023-05-20', '15:00:00', 'Su colaboración es crucial para nuestro éxito.'),
('Organización Epsilon', 'Reunión de Evaluación', '2023-05-25', '11:00:00', 'Sala E', 'David López', 'Natalia Ríos', 'Cristina, Daniel, Irene', 'Víctor, Paula', 'Sergio, Elena', '1. Evaluación de Desempeño\n2. Feedback de Equipos\n3. Plan de Mejora', 'Se evaluaron los desempeños individuales y de equipo, y se dio feedback.', 'Planificación de sesiones de formación.', '2023-06-25', '13:00:00', 'Seguiremos trabajando en nuestras áreas de mejora.'),
('Organización Zeta', 'Reunión de Proyecto', '2023-06-10', '10:00:00', 'Sala F', 'Sofía Martínez', 'Manuel García', 'Victoria, Álvaro, Julia', 'Pablo, Teresa', 'Marcos, Alicia', '1. Estado del Proyecto\n2. Problemas Encontrados\n3. Próximos Pasos', 'Se revisaron los problemas encontrados y se planificaron los próximos pasos.', 'Propuesta de soluciones a problemas actuales.', '2023-07-10', '12:00:00', 'Gracias por su dedicación y esfuerzo.'),
('Organización Eta', 'Reunión de Innovación', '2023-07-15', '14:00:00', 'Sala G', 'Mario Gutiérrez', 'Claudia Méndez', 'Beatriz, Gabriel, Laura', 'Luis, Marta', 'Enrique, Sara', '1. Ideas Innovadoras\n2. Evaluación de Propuestas\n3. Selección de Proyectos', 'Se discutieron y evaluaron varias ideas innovadoras.', 'Implementación de las ideas seleccionadas.', '2023-08-15', '16:00:00', 'Esperamos ver grandes avances en nuestros nuevos proyectos.'),
('Organización Theta', 'Reunión de Formación', '2023-08-20', '09:00:00', 'Sala H', 'Elena Gómez', 'José Rodríguez', 'Raquel, Antonio, Andrea', 'Álvaro, Patricia', 'Ignacio, Claudia', '1. Plan de Formación\n2. Necesidades del Equipo\n3. Calendario de Sesiones', 'Se discutió el plan de formación y las necesidades del equipo.', 'Organización de talleres y cursos.', '2023-09-20', '11:00:00', 'Agradecemos su interés en el desarrollo personal y profesional.'),
('Organización Iota', 'Reunión de Seguimiento', '2023-09-05', '13:00:00', 'Sala I', 'Lucía Romero', 'David Martínez', 'Carlos, Silvia, Javier', 'Fernando, Susana', 'Marina, Jorge', '1. Seguimiento de Tareas\n2. Evaluación de Resultados\n3. Ajustes Necesarios', 'Se revisaron las tareas asignadas y se evaluaron los resultados obtenidos.', 'Planificación de nuevas tareas.', '2023-10-05', '15:00:00', 'Continuaremos con el seguimiento regular de nuestras actividades.'),
('Organización Kappa', 'Reunión de Cierre', '2023-10-20', '11:00:00', 'Sala J', 'Andrea López', 'Ricardo Pérez', 'Miriam, Gonzalo, Sandra', 'Laura, Hugo', 'Tomás, Carolina', '1. Resumen del Año\n2. Logros y Desafíos\n3. Planes Futuro', 'Se hizo un resumen de los logros y desafíos enfrentados durante el año.', 'Planificación de objetivos para el próximo año.', '2023-11-20', '13:00:00', 'Gracias por un año de arduo trabajo y dedicación.');

-- Finalizar las transacciones
COMMIT;
